name: CI

on:
  push:
    branches:
      - master
    tags:
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: install dependencies
      run: npm install
    - name: publish package
      run: npx vsce publish
